M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-06-29T22:17:35+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-29T22:17:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X3.7992Y-2.1299
X4.1142Y-2.1299
T2
X2.685Y-2.0827
X2.685Y-2.3583
M30
