M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Pá 3. května 2024, 14:30:56
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-03T14:30:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.7992Y-2.0876
X4.1142Y-2.0876
T2
X2.685Y-2.0827
X2.685Y-2.3583
M30
